project:
  type: website

execute:
  freeze: auto

website:
  title: "PMEAL"
  navbar:
    logo: _static/logo.png  
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - research.qmd
      - blog.qmd
      - pages/about.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

resources:
  - CNAME
